### PR TITLE
Change Normal font to Carlito Bold from Calibri Bold

### PR DESCRIPTION
**Pull request by EsreverWoW**
Swaps out the normal font for a font-met­ric com­pat­i­ble re­place­ment for Cal­ibri due to licensing issues from the use of Calibri.
- - -
Sourced from [http://gsdview.appspot.com/chromeos-localmirror/distfiles/crosextrafonts-carlito-20130920.tar.gz](http://gsdview.appspot.com/chromeos-localmirror/distfiles/crosextrafonts-carlito-20130920.tar.gz).

### CODE REVIEW

**Comment by Wetxius** [comment]
Is there a difference in how the text looks?

**Comment by Wetxius** [comment]
As I see this font shows number not good.

**Comment by EsreverWoW** [comment]
I had mainly intended to find a nice drop-in replacement for the existing Calibri font since [redistribution in this form requires a specialty license](https://docs.microsoft.com/en-us/typography/font-list/calibri). Some other options might be found the [Google Fonts repository](https://fonts.google.com/?category=Sans+Serif).

Some other decent options might be:

- [Open Sans](https://fonts.google.com/specimen/Open+Sans)
- [Roboto](https://fonts.google.com/specimen/Roboto)
- [PT Sans](https://fonts.google.com/specimen/PT+Sans)
- [Noto Sans](https://fonts.google.com/specimen/Noto+Sans)

Since they may not follow the same metrics, changes to files such as [`ShestakUI\Modules\Blizzard\Fonts.lua`](https://github.com/Shestak/ShestakUI/blob/master/ShestakUI/Modules/Blizzard/Fonts.lua) and anywhere `C.media.normal_font` is referenced may need a font height adjustment.

**Comment by Wetxius** [comment]
FiraSansCondensed-SemiBold.ttf looks good.
https://fonts.google.com/specimen/Fira+Sans+Condensed

**Comment by Wetxius** [comment]
Calibri http://picplus.ru/img/1904/09/093f5442.jpg
Fira Sans Condensed http://picplus.ru/img/1904/09/f3e7c797.jpg
PT Sans Narrow http://picplus.ru/img/1904/09/36306b8e.jpg

**Comment by EsreverWoW** [comment]
Fira Sans looks nice and fairly close. I'll see about adjusting some heights to reflect similarly to how it currently is presented.

**Comment by Wetxius** [comment]
I think that users could get used to the old font. And for many years of its use, we have not had problems with licensing. I created a poll on the forum to get an opinion.

**Comment by Wetxius** [comment]
I decided not to change the font, but thanks for the effort.

**Pull request closed without merging**
