### PR TITLE
Skinned some buttons

### PR DESCRIPTION
**Pull request by lanseb**
Before: https://s14.postimg.org/awizu48n5/Before.jpg

After: https://s14.postimg.org/dckt7yqpr/After.jpg

### CODE REVIEW

**Comment by Wetxius** [comment]
Try T.SkinTab(EncounterJournalInstanceSelectSuggestTab) for tabs.

**Comment by Wetxius** [comment]
:SkinButton(true) use only for button, that have extra texture.
Try without "true"
EncounterJournal.LootJournal.LegendariesFrame.ClassButton:SkinButton()
EncounterJournal.LootJournal.LegendariesFrame.SlotButton:SkinButton()

**Comment by lanseb** [comment]
When you remove true for ClassButton & SlotButton, the skinning breaks:

https://s4.postimg.org/v66v8gbwr/Wo_WScrn_Shot_040817_170303.jpg

You can also see the result of T.SkinTab in that screenshot. Doesn't look good.

**Comment by Wetxius** [comment]
What about T.SkinTab(EncounterJournalInstanceSelectSuggestTab, true)

**Comment by Wetxius** [comment]
SkinButton is bad for tabs, because had extra border on mouseover.

**Comment by lanseb** [comment]
Yes that looks better!

**Pull request closed without merging**
