### PR TITLE
Skin GarrisonLandingPageShipFollowerListListScrollFrameScrollBar

### PR DESCRIPTION
**Pull request by lanseb**

### CODE REVIEW

**Comment by lanseb** [comment]
Wetxius --

Any chance you could take a look at the scrollbar for the "other characters" frame created by the addon MasterPlan? I tried to do a /fstack but it's not showing the name of the scrollbar, so I can't figure out how to skin it. :\

Thanks!

**Comment by lanseb** [comment]
Here is a screenshot with fstack:

http://tinyurl.com/flux02

**Comment by Wetxius** [comment]
I can't help, because frame has not global name. Bad coding, imo.

**Comment by lanseb** [comment]
Thanks for looking into it! I will try to contact the addon creator for MasterPlan and see if he can do anything about it!

I'll keep you updated :)

**Comment by Wetxius** [comment]
Need something like this https://github.com/Shestak/ShestakUI/blob/master/ShestakUI_Config/ShestakUI_Config.lua#L799-L820
This scroll has name UIConfigGroupSlider

**Comment by lanseb** [comment]
The latest version of Master Plan changed the scroll bars, but I don't know if it fixed the issue or not. I wasn't able to skin the scroll bars after trying again.

**Comment by Wetxius** [comment]
MissionsUI.lua :1708 line
local sf, sc, bar = CreateFrame("ScrollFrame", nil, parent) do
"nil" is therefore it does not have a name.

**Pull request merged**
