### PR TITLE
Update RaidAuraWatch.lua

### PR DESCRIPTION
**Pull request by leg883**

### CODE REVIEW

**Comment by Shestak** [comment]
Can you translate the description into English?

**Comment by leg883** [comment]
OK, I will try.Do you give up this project?

**Comment by Shestak** [comment]
This pull? Yes, but only in English desc.
Anyway, thank you very much for your pulls.

**Comment by leg883** [comment]
DBM skin was some errors , can you fix them ? I say, Did you give up ShestakUI ?

**Comment by Shestak** [comment]
No, I have no more free time for the ShestakUI.

**Comment by leg883** [comment]
I wanted to improve the ShestakUI, but I'm not familiar with lua.

**Comment by leg883** [comment]
If you have free time, try to fix DBM skin, please.

**Comment by Shestak** [comment]
Please, desc only in English.

**Comment by leg883** [comment]
And Cooldowns.lua ？

**Comment by Shestak** [comment]
Yes.

**Comment by leg883** [comment]
ShestakUI still needs a little bit of work.

**Pull request merged**
