### PR TITLE
Update AuraTracker to manage no timer cases on ArenaFrame auras

### PR DESCRIPTION
**Pull request by AlbertDuval**
Grounding Totem for example

### CODE REVIEW

**Comment by Wetxius** [comment]
What it did? It hide Grounding Totem icon or hide only timer?

**Comment by AlbertDuval** [comment]
Hide only timer, without this fix, their a red bug on shown text, with my
fix, you just have an icon while arena players are under an untimed buff.

**Comment by Wetxius** [comment]
Maybe better using this?
```lua
		object.AuraTracker.icon:SetTexture(auraIcon)
		object.AuraTracker.timeleft = auraExpTime - GetTime()
		if object.AuraTracker.timeleft > 0 then
			object.AuraTracker.active = true
		end
```

**Comment by AlbertDuval** [comment]
Does the icon still visible while AuraTracker unactivated ?

**Comment by Wetxius** [comment]
I can't test on live)

**Comment by AlbertDuval** [comment]
I tested on live, it works, it's much cleaner than mine

**Comment by Wetxius** [comment]
Apply https://github.com/Shestak/ShestakUI/commit/0ae9194f8c7175b1e720042ae5e83911477237df
Thanks for testing.

**Pull request closed without merging**
