### PR TITLE
Fixing Nameplates

### PR DESCRIPTION
**Pull request by AlbertDuval**
Conditioning old customization lists to solve bad argument error

### CODE REVIEW

**Comment by Wetxius** [comment]
Why you getting error? This table are creating in https://github.com/Shestak/ShestakUI/blob/master/ShestakUI/Core/GUI.lua#L37-L38

**Comment by AlbertDuval** [comment]
I find the issue, it's because I'm playing without ShestakUI_Config (b/c all my settings are hardcoded into Settings.lua), so the 2nd line of GUI.lua bypass the initialization sequence:
if not IsAddOnLoaded("ShestakUI_Config") then return end

**Comment by Wetxius** [comment]
So you should getting raid debuff error too? And all other spell lists. Need move checking bellow

**Comment by AlbertDuval** [comment]
Yes exactly I had other issues with Annoucements, Cooldowns, RaidAuraWatch and Filger. I just commented entire blocks.
By moving the initialization sequence before the return it solves all issues.

**Comment by Wetxius** [comment]
I'll fix it tomorrow.

**Comment by AlbertDuval** [comment]
Unrelevant fix

**Pull request closed without merging**
