### PR TITLE
Some fix

### PR DESCRIPTION
**Pull request by 61115111**
1.Fix double icon for monk
2.Remove useless arua
3.Remove same spell for Kil'Jaeden

### CODE REVIEW

**Comment by Wetxius** [comment]
It bad fix. You should remove second Fortifying Brew spell instead of checking by spell id and add only one line for cooldown, because Filger check spell by name.

**Comment by 61115111** [comment]
It's different spell for each talent, and it's also have different cd and spell icon.

**Comment by Wetxius** [comment]
It's not matter. Just add only one spell and check for different talent.

**Comment by 61115111** [comment]
I have done it before, and I found Fortifying Brew is a yellow spell icon in Brewmaster talent and blue spell icon in Mistweaver. I think that if only check spell name will cause misunderstanding, so check spell id now.

**Comment by Wetxius** [comment]
Filger check only spell name. If you add 120954 Fortifying Brew and Filger parse your buff and found any spell with this name, Filger shows it, no matter what icon.

**Comment by 61115111** [comment]
I know what your means.But 120954 Fortifying Brew and 243435 Fortifying Brew not the same spell.it's not like Frostbolt(lv.1) Frostbolt(lv.2) was same spell,it's just different spell in each talent use a same name.

**Comment by 61115111** [comment]
Thx, I temporarily close this pull. Maybe I focused on the cd icon to ignore this part mistake.

**Pull request closed without merging**
