### PR TITLE
Added Elixir of Rapid Mind [XP]

### PR DESCRIPTION
**Pull request by lanseb**
Added 'Elixir of Rapid Mind' to the Experience & Reputation section. Some cleanup.

### CODE REVIEW

**Comment by Tryllemann** [comment]
This isn't something that should be added from my point of view.
This is a normal longtime buff.

**Comment by lanseb** [comment]
Um. Every other XP buff is part of the Spells file. They are all there for the same reason: to maximize the uptime on EXPERIENCE.

If you took the time to look up the Elixir of Rapid Mind on WowHead, you would see that it is an Elixir that lasts ONLY 15 mins. It is particularly important to know when it expires.

**Comment by Tryllemann** [comment]
I know perfectly what it is. Both this and guild rep shouldn't be inside filger. This is easy to track by looking on ur buff frame.
This has nothing todo with why filger is made in the first place.
Im sure if Shestak agree with you he will merge it.

**Comment by Shestak** [comment]
The question I cant decide. I still do not play.

**Comment by lanseb** [comment]
It's just an addition to an already existing section of the spells file: "Experience & Reputation". I added said section a few months ago.

All of the buffs are there except the new Elixir XP buff. So when you do decide I guess what you should be deciding on is: keep the section or no? If you don't add this, you might as well remove the others.

It's fine by me either way, I have them backed up for my own spells file.

**Comment by Tryllemann** [comment]
Are there actualy any none important buff in the game. If you are going to add all buffs to filger, then you can simply move buff frame down. Filger is there to provide combat related buff/debuffs that affects damage done or dmg taken so that players don't need to filter stuff themself from buff frame and target frame. If i have aproved Expericen related stuff then it's by failure from me. 
Me not adding this is my view of why filger exist.

Where you have it that i don't play the game beats me, i had a breake thats all. I have 4x WoD accounts and 3x Mop accounts and total of 17x lvl 100. I mostly enjoy leveling in wow. And i have NEVER missed such spells on filger! I manages just fine to look at buffs for this.

If this is the normal reaction lanseb that you throw everytime someone doesn't agree with you then maybe drop it?

**Comment by lanseb** [comment]
Am I gonna have to re-quote my earlier post?

"It's fine by me either way, I have them backed up for my own spells file."

There's nothing more to be said, I'm just waiting for Shestak to decide since it's his UI. Drop it.

**Pull request closed without merging**
